### ISSUE TITLE
rawread can't handle single sided disks without being told

### ISSUE THREAD

**Issue by jepler** [davidgiven/fluxengine#429]
I dumped a Commodore 1541 disk and also saved the flux:
```
./fluxengine read  commodore1541 --copy-flux-to archon.flux -o archon.d64
```
Then later I wanted to convert the flux to scp format for experimentation, but it crashes.
```
Starting program: /home/jepler/src/fluxengine/fluxengine-debug rawread -s archon.flux -d archon.scp
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
SCP: writing 96 tpi double sided file containing 160 tracks
  0.0: 200 ms in 64741 bytes
  0.1: 
Program received signal SIGSEGV, Segmentation fault.
0x000055555558850a in Bytes::size (this=0x10) at lib/bytes.h:25
25	    unsigned size() const        { return _high - _low; }
(gdb) where
#0  0x000055555558850a in Bytes::size (this=0x10) at lib/bytes.h:25
#1  0x0000555555588536 in Fluxmap::bytes (this=0x0) at lib/fluxmap.h:41
#2  0x0000555555612940 in readFluxmap (fluxsource=..., cylinder=0, head=1) at lib/reader.cc:31
#3  0x0000555555614b50 in rawReadDiskCommand (fluxsource=..., fluxsink=...) at lib/reader.cc:227
#4  0x000055555558dbcc in mainRawRead (argc=5, argv=0x7fffffffe110) at src/fe-rawread.cc:72
#5  0x0000555555576f4f in main (argc=6, argv=0x7fffffffe108) at src/fluxengine.cc:134
```
I suspect that this occurs because the image doesn't contain any flux data for head 1.

Note: it's not likely to be relevant, but I'm doing the original dump using Adafruit's prototype floppy interface board & software. The actual command shown above was with revision dbfc0f9.

The process will run to completion but only if I specify `-h 0` to use just one head.

**Comment by davidgiven** [comment]
Yup, that's clearly a bug. I'll take a look.
