### ISSUE TITLE
Build fails on Mac Sonoma

### ISSUE THREAD

**Issue by rogermc2** [davidgiven/fluxengine#779]
Mac Silicon M3
OSX Sonoma 14.7
XCode 15.4

gmake failed with:
fluxengine-master % gmake               
AB
loading build.py
loading build/c.py
loading build/utils.py
loading build/protobuf.py
loading build/pkg.py
Traceback (most recent call last):
  File "/System/Volumes/Data/Applications_Packages/fluxengine-master/build/ab.py", line 548, in <module>
    main()
  File "/System/Volumes/Data/Applications_Packages/fluxengine-master/build/ab.py", line 540, in main
    loadbuildfile(f)
  File "/System/Volumes/Data/Applications_Packages/fluxengine-master/build/ab.py", line 359, in loadbuildfile
    builtins.__import__(filename)
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/System/Volumes/Data/Applications_Packages/fluxengine-master/build/ab.py", line 67, in exec_module
    super(SourceFileLoader, self).exec_module(module)
  File "build.py", line 3, in <module>
    from build.protobuf import proto, protocc
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/System/Volumes/Data/Applications_Packages/fluxengine-master/build/ab.py", line 67, in exec_module
    super(SourceFileLoader, self).exec_module(module)
  File "build/protobuf.py", line 13, in <module>
    assert build.pkg.TargetPkgConfig.has_package(
AssertionError: required package 'protobuf' not installed
gmake: *** No rule to make target '+all', needed by 'all'.  Stop.

protobuf is installed.
Brew says that there is no package truncate,

**Comment by davidgiven** [comment]
I think newer OSX has truncate now? Certainly my Sequoia test system seems to have it in /usr/bin.

Re the missing protobuf package: you sure you installed it through homebrew? What does `brew list protobuf` say?
