### ISSUE TITLE
FluxEngine client does not build on Linux (Debian 11)

### ISSUE THREAD

**Issue by Holger6504** [davidgiven/fluxengine#788]
Hi,
I'm trying to build the FluxEngine client on Linux, but get the following error regarding the module
 named build.c.  Dependencies and Python installation seems to be ok.
Can you help me solve this problem.
Best regards
Holger

_AB
loading build.py
Traceback (most recent call last):
  File "/home/holger/Tools/FloppyTools/fluxengine/build/ab.py", line 548, in <module>main()
  File "/home/holger/Tools/FloppyTools/fluxengine/build/ab.py", line 540, in main loadbuildfile(f)
  File "/home/holger/Tools/FloppyTools/fluxengine/build/ab.py", line 359, in loadbuildfile builtins.__import__(filename)
  File "/home/holger/Tools/FloppyTools/fluxengine/build/ab.py", line 67, in exec_module super(SourceFileLoader, self).exec_module(module)
  File "build.py", line 2, in <module> from build.c import clibrary, cxxlibrary
**ModuleNotFoundError: No module named 'build.c'**
make: *** Keine Regel vorhanden, um das Ziel „+all“, benötigt von „all“, zu erstellen.  Schluss._

**Comment by davidgiven** [comment]
That should not be happening. Could you show me the result of `python3 --version`, please? Also, the command line you're using to do the build?

**Comment by Holger6504** [comment]
$ python3 --version
Python 3.9.2
The command line is just “make” with no parameters.

Best regards
Holger

**Comment by Holger6504** [comment]
Ok, upgradet to Python Python 3.12.3
Looks better, but...

holger@FUJITSU22:~/Tools/FloppyTools/fluxengine-dev$ make
[1/371] CXX src/+fluxengine/src/fe-analyselayout.cc
[2/371] CXX src/+fluxengine/src/fe-format.cc
[3/371] CXX src/+fluxengine/src/fe-getdiskinfo.cc
[4/371] CXX src/+fluxengine/src/fe-getfile.cc
[5/371] CXX src/+fluxengine/src/fe-getfileinfo.cc
[6/371] CXX src/+fluxengine/src/fe-inspect.cc
[7/371] CXX src/+fluxengine/src/fe-ls.cc
[8/371] CXX src/+fluxengine/src/fe-merge.cc
In file included from src/fe-getdiskinfo.cc:4:
.obj/host/lib/data/+data_hdr/lib/data/sector.h: In member function ‘auto fmt::v7::formatter<Sector::Status>::format(Sector::Status, fmt::v7::format_context&) const’:
.obj/host/lib/data/+data_hdr/lib/data/sector.h:99:48: **error: passing ‘const fmt::v7::formatter<Sector::Status>’ as ‘this’ argument discards qualifiers [-fpermissive]**
   99 |             Sector::statusToString(status), ctx);
      |                                                ^
In file included from .obj/host/lib/core/+core_hdr/lib/core/globals.h:19,
                 from src/fe-getdiskinfo.cc:1:
...
Error repeats

**Comment by davidgiven** [comment]
That one sounds like your C++ compiler issues. FluxEngine is written using, mostly, C++17 which your compiler ought to support but it's possible that your libfmt isn't compatible with C++17. Can you make sure your libfmt-dev package is at least version 8?
